### ISSUE TITLE
Домашка №1, HTML

### ISSUE THREAD

**Issue by tiny-kottan** [ElegantElephant44/kottans-js-2016#3]
Разметить эту страницу: https://habrahabr.ru/post/244929/
от вас ожидаеться `.html` файл с семантичной разметкой, без css/js
крупные части контента копипастить не стоит (саму статью, там `h*`/`p`/`code` -- все просто), а вот остальное -- нужно
как должно выглядить

`````` html
<!doctype html>
<html lang=ru>
<meta charset=utf-8>
<title>Habrahabr.ru</title>
<header>
  <ul>
    <li><a href=...>TM Feed</a>
    <li><a>Хабрахабр</a>
  </ul>```
``````

**Comment by ElegantElephant44** [comment]
https://github.com/ElegantElephant44/kottans-js-2016/tree/master/week01/homework1

**Comment by mkozhukharenko** [comment]
here is a mess with `nav`s https://github.com/ElegantElephant44/kottans-js-2016/blob/master/week01/homework1/habrPost244929.html#L20-L53
you need two wrap only one list with nav
You should watch a video from a lesson one more time 😸

**Comment by mkozhukharenko** [comment]
I think that it is not necessary to use a figure here. 
https://github.com/ElegantElephant44/kottans-js-2016/blob/master/week01/homework1/habrPost244929.html#L62-L72

**Comment by mkozhukharenko** [comment]
read this, please https://github.com/vrd/kottans-js-2016/issues/2#issuecomment-221053597

**Comment by mkozhukharenko** [comment]
You can use `sup` for this https://github.com/ElegantElephant44/kottans-js-2016/blob/master/week01/homework1/habrPost244929.html#L117 as @vrd do.

**Comment by mkozhukharenko** [comment]
do you really need those fieldset? 
https://github.com/ElegantElephant44/kottans-js-2016/blob/master/week01/homework1/habrPost244929.html#L197

**Comment by mkozhukharenko** [comment]
dont use aside as a wrapper
https://github.com/ElegantElephant44/kottans-js-2016/blob/master/week01/homework1/habrPost244929.html#L212

https://github.com/vrd/kottans-js-2016/issues/2#issuecomment-221067829:

>  Aside is not a sidebar or wrapper for random stuff - it's container for secondary(secondary to main article or website)!

**Comment by ElegantElephant44** [comment]
@mkozhukharenko I agree, that `figure` is not necessary here https://github.com/ElegantElephant44/kottans-js-2016/blob/master/week01/homework1/habrPost244929.html#L62-L72, but how to show the logical link between caption and value?

**Comment by mkozhukharenko** [comment]
try smth like this:

``` html
<figure>
          <meter value=2 min=-3000 max=3000>
                <span> карма </span>
               <span> карма 2,0 </span>
          </meter>
</figure>

```

I'm not sure if it'll work, but let's give a try 😄 
please, read a spec and give a short conclusion if it's correct
