### ISSUE TITLE
Фидбек на домашку №2

### ISSUE THREAD

**Issue by tiny-kottan** [ElegantElephant44/kottans-js-2016#5]
`let html =fs.readFileSync(argv[0], 'utf8')` -> can be easily `const`, add space after '='

```
let bootstrapClass;
for (let i = 0; i < bootstrapClasses.length; i++) {
    bootstrapClass = bootstrapClasses[i]
    …
```

there's more conventient way of doing this `for (let bootstrapClass of bootstrapClasses)`

Pattern of 

```
let jsDataResultString="";
       for (let i = 0; i < jsDataAttrs.length; i++) {
           classes = classes.replace(jsDataAttrs[i],"")
           jsDataResultString = jsDataResultString.concat(jsDataAttrs[i].substring(3))
       }
```

looks like a good place for [Array#reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce)

```
if(jsDataAttrs != null)
{
```

vs

```
if(classes!=""){
```

try to be consistent

**Comment by ElegantElephant44** [comment]
Remade https://github.com/ElegantElephant44/kottans-js-2016/blob/master/week01/homework2/posthtml.js
